export const setStandardDesignCard = ( setSettings ) => {
	setSettings({
		layout: 'card',
		maxWidth: 500,
		padding: 28,
		borderRadius: 6,
		titleFontSize: 22,
		descriptionFontSize: 14,
		titleNumOfChar: 38,
		descriptionNumOfChar: 120,
		gapBetweenTitleAndThumbnail: 6,
		descriptionMarginTop: 6,
		shadowUse: 'none',
		shadowOffsetX: 2,
		shadowOffsetY: 3,
		shadowBlurRadius: 3,
		shadowSpreadRadius: 3,
		shadowColor: '#0000001a',
		hoverUse: 'shadow',
		hoverTop: 5,
		hoverTransitionTime: 0.3,
		hoverShadowOffsetX: 0,
		hoverShadowOffsetY: 2,
		hoverShadowBlurRadius: 3,
		hoverShadowSpreadRadius: 3,
		hoverShadowColor: '#0000000d',
	})
}

export const setStandardDesignList = ( setSettings ) => {
	setSettings({
		layout: 'list',
		maxWidth: 600,
		padding: 12,
		borderRadius: 8,
		titleFontSize: 19,
		descriptionFontSize: 15,
		titleNumOfChar: 38,
		descriptionNumOfChar: 120,
		gapBetweenTitleAndThumbnail: 12,
		descriptionMarginTop: 6,
		shadowUse: 'none',
		shadowOffsetX: 2,
		shadowOffsetY: 3,
		shadowBlurRadius: 3,
		shadowSpreadRadius: 3,
		shadowColor: '#0000001a',
		hoverUse: 'shadow',
		hoverTop: 5,
		hoverTransitionTime: 0.3,
		hoverShadowOffsetX: 0,
		hoverShadowOffsetY: 2,
		hoverShadowBlurRadius: 3,
		hoverShadowSpreadRadius: 3,
		hoverShadowColor: '#0000001a',
	})
}

export const setRecommendedDesign2 = ( setSettings ) => {
	setSettings({
		layout: 'list',
		borderRadius: 0,
		shadowOffsetX: 0,
		shadowOffsetY: 0,
		shadowBlurRadius: 0,
		shadowSpreadRadius: 0,
		shadowColor: '#00000000',
		hoverUse: 'shadow',
		hoverTop: 5,
		hoverTransitionTime: 0.3,
		hoverShadowOffsetX: 0,
		hoverShadowOffsetY: 2,
		hoverShadowBlurRadius: 3,
		hoverShadowSpreadRadius: 3,
		hoverShadowColor: '#0000001a',
	})
}
