name: Create Tag on Version Update

on:
  push:
    paths:
      - 'package.json'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract package version and check for change
        id: vars
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          PREV_PACKAGE=$(git show HEAD^:package.json 2>/dev/null || echo '{}')
          PREV_VERSION=$(echo "$PREV_PACKAGE" | jq -r '.version')
          
          if [ "$PREV_VERSION" = "$VERSION" ]; then
            echo "Version not changed (previous: $PREV_VERSION, current: $VERSION), skipping tag creation."
            exit 0
          else
            echo "Version updated from $PREV_VERSION to $VERSION"
          fi

      - name: Create and push Git tag using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          TAG=v${{ env.VERSION }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag $TAG
            git push https://${GH_PAT}@github.com/${{ github.repository }}.git $TAG
          fi

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          body: "Release for version ${{ env.VERSION }}"
