name: Create Tag on Version Update

on:
  push:
    paths:
      - 'package.json'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract package version and check for change
        id: vars
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          PREV_PACKAGE=$(git show HEAD^:package.json 2>/dev/null || echo '{}')
          PREV_VERSION=$(echo "$PREV_PACKAGE" | jq -r '.version')
          
          if [ "$PREV_VERSION" = "$VERSION" ]; then
            echo "Version not changed (previous: $PREV_VERSION, current: $VERSION), skipping tag creation."
            exit 0
          else
            echo "Version updated from $PREV_VERSION to $VERSION"
          fi

      - name: Create and push Git tag
        run: |
          TAG=v${{ env.VERSION }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
          else
            git tag $TAG
            git push origin $TAG
          fi
