name: Create Tag on Version Update

on:
  push:
    paths:
      - 'package.json'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract package version and check for change
        id: vars
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          PREV_VERSION=$(git show HEAD^:package.json | jq -r '.version' || echo "")
          
          if [ "$PREV_VERSION" = "$VERSION" ]; then
            echo "Version not changed (previous: $PREV_VERSION, current: $VERSION), skipping tag creation."
            exit 0
          else
            echo "Version updated from $PREV_VERSION to $VERSION"
          fi

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "v${VERSION}"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} "v${VERSION}"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${VERSION}" --title "v${VERSION}" --notes "Release ${VERSION}"

      - name: Trigger SVN Deploy
        run: |
          curl -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
           https://api.github.com/repos/${{ github.repository }}/dispatches \
           -d '{"event_type": "deploy-svn", "client_payload": {"version": "${VERSION}"}}'
