name: SVN Commit

on:
  push:
    branches:
      - main

jobs:
  svn-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Install Subversion and SubGit
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion
        wget https://subgit.com/files/subgit-3.3.11.zip
        unzip subgit-3.3.11.zip
        sudo mv subgit-3.3.11/bin/subgit /usr/local/bin
        sudo chmod +x /usr/local/bin/subgit

    - name: Configure Git-SVN
      run: |
        subgit configure --svn-url https://plugins.svn.wordpress.org/custom-card-link --trunk main --layout auto --authors-file AUTHORS.txt --non-interactive git-svn
        echo "password = ${{ secrets.SVN_PASSWORD }}" >> git-svn/subgit/passwd
        echo "username = ${{ secrets.SVN_USERNAME }}" >> git-svn/subgit/passwd
        echo "sslVerify = false" >> git-svn/subgit/config
        subgit install git-svn

    - name: Sync with SVN
      run: |
        cd git-svn
        git fetch origin
        git merge origin/main
        git svn dcommit
