name: SVN Commit

on:
  push:
    branches:
      - main

jobs:
  svn-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SVN client
        run: sudo apt-get install subversion

      - name: Set up SVN client
        run: |
          mkdir -p ~/.subversion
          echo "[auth]" > ~/.subversion/servers
          echo "password-stores =" >> ~/.subversion/servers
          echo "store-plaintext-passwords = no" >> ~/.subversion/servers
          echo "username = ${{ secrets.SVN_USERNAME }}" > ~/.subversion/auth
          echo "password = ${{ secrets.SVN_PASSWORD }}" >> ~/.subversion/auth
          echo "store-passwords = no" >> ~/.subversion/auth

      - name: Checkout svn
        run: |
          cd ~
          mkdir custom-card-link
          cd custom-card-link
          svn checkout https://plugins.svn.wordpress.org/custom-card-link .

      - name: Commit changes to SVN
        run: |
          cp -r ${{ github.workspace }}/. ~/custom-card-link/trunk/
          cd ~/custom-card-link/trunk
          svn add * --force
          svn commit -m "commit message" --no-auth-cache --non-interactive
        env:
          SVN_CONFIG_DIR: "./"
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
